behaviors:
  rocket landing:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    # behavior cloning
    behavioral_cloning:
      demo_path: "demo/NewLanding.demo"
      strength: 0.5
      steps: 150000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

      # curiosity module
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4

      # GAIL
      gail:
        strength: 0.5
        gamma: 0.99
        encoding_size: 128
        demo_path: "demo/NewLanding.demo"
        learning_rate: 3.0e-4
        use_actions: false
        use_vail: false

    # self-play
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 2000
      team_change: 100000


# behaviors:
#   rocket landing:
#     trainer_type: ppo
#     hyperparameters:
#       batch_size: 1024
#       buffer_size: 10240
#       learning_rate: 0.0003
#       beta: 0.01
#       epsilon: 0.2
#       lambd: 0.95
#       num_epoch: 3
#       shared_critic: false
#       learning_rate_schedule: linear
#       beta_schedule: linear
#       epsilon_schedule: linear
#     checkpoint_interval: 500000
#     network_settings:
#       normalize: false
#       hidden_units: 128
#       num_layers: 2
#       vis_encode_type: simple
#       memory: null
#       goal_conditioning_type: hyper
#       deterministic: false
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0
#         network_settings:
#           normalize: false
#           hidden_units: 128
#           num_layers: 2
#           vis_encode_type: simple
#           memory: null
#           goal_conditioning_type: hyper
#           deterministic: false
#     #   gail:
#     #     strength: 0.2
#     #     demo_path: "demo/NewLanding.demo"
#     # behavioral_cloning:
#     #   strength: 0.2
#     #   demo_path: "demo/NewLanding.demo"
#     init_path: null
#     keep_checkpoints: 5
#     even_checkpoints: false
#     max_steps: 500000
#     time_horizon: 64
#     summary_freq: 20000
#     threaded: false
#     self_play: null
# env_settings:
#   env_path: null
#   env_args: null
#   base_port: 5005
#   num_envs: 1
#   num_areas: 1
#   timeout_wait: 60
#   seed: -1
#   max_lifetime_restarts: 10
#   restarts_rate_limit_n: 1
#   restarts_rate_limit_period_s: 60
# engine_settings:
#   width: 84
#   height: 84
#   quality_level: 5
#   time_scale: 20
#   target_frame_rate: -1
#   capture_frame_rate: 60
#   no_graphics: false
#   no_graphics_monitor: false
# environment_parameters: null
# # checkpoint_settings:
# #   run_id: test3
# #   initialize_from: null
# #   load_model: false
# #   resume: false
# #   force: true
# #   train_model: false
# #   inference: false
# #   results_dir: results
# # torch_settings:
# #   device: null
# # debug: false